### ISSUE TITLE
A few issues

### ISSUE THREAD

**Issue by MaxKaboom** [ForOhForError/Yet-Another-Magic-Card-Recognizer#5]
Hi! I downloaded this to use for streaming paper magic. I'm having trouble with a few things. The program doesn't want to "load" more than about 8 sets at once. After this, it just sits on "1 set loading" for a long time and does nothing.

I also cannot see the buttons you're talking about like the browser button or the create custom set button. It could be my own reading. Thank you for whatever reply you can offer!

**Comment by ForOhForError** [comment]
I wasn't able to reproduce an inability to load multiple sets. It may help to select "Only Trigger Recognition Manually" before loading set files, though the synchronization mechanisms in place should catch any potential issues anyway.

The readme file was updated ahead of any actual release with upcoming features. Since I was not actively developing YamCR for some time, this meant the released version was significantly out of date compared to the feature set on the project page. I've pushed a pre-release build that makes these features available. Note that it uses a new set format, necessitating re-generation of set files. The included features may still be unstable, as they haven't had any polishing in the time since I was developing them.

If you still have trouble loading sets after updating, please include the ```errorlog.txt``` file in the YamCR directory in this issue.
